# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSWjkQzzYmWvi3X0IAHKZ0BA2_8PTcZG
"""

usuarios = []

def cadastrar_usuario():

  nome = input("digite seu nome: ")
  idade = int(input("digite sua idade:"))
  email = input("digite seu email:")

  usuario = {
      "nome" : nome,
      "idade" : idade,
      "email" : email
  }
  return usuario

for i in range(3):
  print(F"\nCadastro {i + 1}")
  usuarios.append(cadastrar_usuario())

print("\nLinha final de cadastro: ")
for usuario in usuarios:
   print(usuario)